# Generated by Django 5.1.5 on 2026-03-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp_attempts_user_otp_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
