# Generated by Django 5.1.5 on 2026-03-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_roles_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_stripe__0fdd23_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
