# Generated by Django 5.2.10 on 2026-01-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(default='stripe', max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhooks_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='stripeevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stripe Event', 'verbose_name_plural': 'Stripe Events'},
        ),
        migrations.RemoveIndex(
            model_name='stripeevent',
            name='stripe_even_stripe__92510f_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripeevent',
            name='stripe_even_event_t_65f41c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripeevent',
            name='stripe_even_status_dde50c_idx',
        ),
        migrations.AlterModelTable(
            name='stripeevent',
            table='webhooks_stripe_event',
        ),
    ]
