# Generated by Django 5.2.10 on 2026-01-23 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255)),
                ('cache_type', models.CharField(choices=[('overview', 'Overview'), ('costs', 'Costs'), ('maintenance', 'Maintenance'), ('fuel', 'Fuel'), ('diagnostics', 'Diagnostics')], max_length=50)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statistics_cache',
                'indexes': [models.Index(fields=['user', 'cache_type'], name='statistics__user_id_9cee67_idx'), models.Index(fields=['expires_at'], name='statistics__expires_bb7f6b_idx')],
                'unique_together': {('user', 'cache_key')},
            },
        ),
    ]
