# Generated by Django 5.2.10 on 2026-01-23 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0002_initial'),
        ('documents', '0002_initial'),
        ('maintenances', '0002_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_push', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_in_app', models.BooleanField(default=True)),
                ('maintenance_reminders', models.BooleanField(default=True)),
                ('document_expiry_reminders', models.BooleanField(default=True)),
                ('diagnostic_reminders', models.BooleanField(default=True)),
                ('custom_reminders', models.BooleanField(default=True)),
                ('days_before_maintenance', models.IntegerField(default=7)),
                ('days_before_document_expiry', models.IntegerField(default=30)),
                ('reminder_time', models.TimeField(default='09:00:00')),
                ('digest_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('enable_quiet_hours', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00:00')),
                ('quiet_hours_end', models.TimeField(default='08:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='reminders_p_user_id_b6cb30_idx'), models.Index(fields=['token'], name='reminders_p_token_df6e1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('maintenance', 'Maintenance Due'), ('document_expiry', 'Document Expiring'), ('diagnostic_followup', 'Diagnostic Follow-up'), ('custom', 'Custom Reminder')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('remind_at', models.DateTimeField()),
                ('repeat', models.BooleanField(default=False)),
                ('repeat_interval', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='diagnostics.diagnostic')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='documents.document')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='maintenances.maintenance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-remind_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reminders_r_user_id_8beec6_idx'), models.Index(fields=['user', 'remind_at'], name='reminders_r_user_id_d8fad4_idx'), models.Index(fields=['status', 'remind_at'], name='reminders_r_status_066074_idx')],
            },
        ),
    ]
