# Generated by Django 5.2.10 on 2026-01-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='diagnosticreply',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='diagnostics.diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticreply',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='diagnostic',
            index=models.Index(fields=['user'], name='diagnostics_user_id_83522b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostic',
            index=models.Index(fields=['vehicle'], name='diagnostics_vehicle_f41af1_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostic',
            index=models.Index(fields=['status'], name='diagnostics_status_19df6b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreply',
            index=models.Index(fields=['diagnostic', 'created_at'], name='diagnostic__diagnos_ac4a6c_idx'),
        ),
    ]
