# Generated by Django 5.2.10 on 2026-01-23 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('vehicle_summary', 'Vehicle Summary'), ('maintenance_history', 'Maintenance History'), ('diagnostic_history', 'Diagnostic History'), ('cost_analysis', 'Cost Analysis'), ('fuel_consumption', 'Fuel Consumption'), ('comprehensive', 'Comprehensive Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_images', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_details', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reports_rep_user_id_8456e4_idx'), models.Index(fields=['user', 'report_type'], name='reports_rep_user_id_f11f57_idx'), models.Index(fields=['expires_at'], name='reports_rep_expires_6eb760_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('vehicle_summary', 'Vehicle Summary'), ('maintenance_history', 'Maintenance History'), ('diagnostic_history', 'Diagnostic History'), ('cost_analysis', 'Cost Analysis'), ('fuel_consumption', 'Fuel Consumption'), ('comprehensive', 'Comprehensive Report')], max_length=50)),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_images', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('include_details', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='reports_rep_user_id_cd881a_idx')],
            },
        ),
    ]
