# Generated by Django 5.2.10 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE subscriptions DROP COLUMN IF EXISTS plan_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_code',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(default='Free', max_length=100),
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS plans_plan CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
