# Generated by Django 5.1.5 on 2026-03-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='subscription_alerts',
        ),
    ]
