# Generated by Django 5.2.10 on 2026-01-21 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.JSONField(blank=True, help_text='GeoJSON Point: {"type": "Point", "coordinates": [longitude, latitude]}', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'garages',
                'ordering': ['-average_rating', 'name'],
                'indexes': [models.Index(fields=['city'], name='garages_city_2d2e4c_idx'), models.Index(fields=['postal_code'], name='garages_postal__daee79_idx'), models.Index(fields=['-average_rating'], name='garages_average_419958_idx')],
            },
        ),
        migrations.CreateModel(
            name='GarageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='garages.garage')),
            ],
            options={
                'db_table': 'garage_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['garage', '-created_at'], name='garage_revi_garage__a39158_idx')],
            },
        ),
    ]
